import asyncio
import logging

from typing         import List, Dict, Tuple, Optional, Union

from .storage       import MangaStorage, TocRecord
from .schemas       import SearchData
from .client        import MangaLibClient, ChapterNumber
from .telegraph     import TelegraphClient
from .exceptions    import MangagraphError
from .utils         import (
    estimate_remaining_time,
    extract_slug,
    normalize_chapter_number,
    sanitize_db_name
)
from .constants     import TELEGRAPH_CREDS


class Mangagraph():
    """
    Оркестратор: MangaLib API -> Telegraph страницы -> SQLite.

    Запросы к API живут в :class:`MangaLibClient` и доступны напрямую
    через ``self.client``.

    Автор: https://github.com/damirtag

    Репозитории: https://github.com/damirTAG/mangagraph

    Args:
        token: Персональный Bearer-токен MangaLib (нужен для поиска).
            Если не передан — берется из MANGALIB_TOKEN (env или .env).
    """
    def __init__(self, token: Optional[str] = None):
        self.logger     = self._setup_logger()
        self.client     = MangaLibClient(token)
        self.telegraph  = TelegraphClient()

    def _setup_logger(self):
        logger = logging.getLogger('mangagraph')
        handler = logging.StreamHandler()
        formatter = logging.Formatter('[mangagraph]: %(levelname)s - %(message)s')
        handler.setFormatter(formatter)
        if not logger.handlers:
            logger.addHandler(handler)
        logger.setLevel(logging.INFO)
        logger.propagate = False
        return logger

    def _setup_storage(self, db_name: str) -> MangaStorage:
        db_name = sanitize_db_name(db_name)
        self.logger.info(f'Имя БД: {db_name}')
        return MangaStorage(db_name)

    async def _ensure_telegraph_account(self):
        if not self.telegraph.access_token:
            await self.telegraph.create_account(**TELEGRAPH_CREDS)

    async def search_manga(self, query: str, limit: int = 5) -> List[SearchData]:
        """Поиск манги. Тонкая обертка над ``self.client.search``."""
        try:
            async with self.client:
                return await self.client.search(query, limit)
        except MangagraphError as e:
            self.logger.error(f"Ошибка поиска: {e}")
            return []

    async def _create_telegraph_page(
            self,
            title: str,
            image_urls: List[str]
        ) -> Tuple[str, str]:
        content = [{"tag": "img", "attrs": {"src": url}} for url in image_urls]

        try:
            response = await self.telegraph.create_page(
                title=title,
                content=content,
                author_name='Generated by mangagraph',
                author_url='https://github.com/damirTAG/mangagraph'
            )
        except MangagraphError:
            raise
        except Exception as e:
            raise MangagraphError(f"Не удалось создать telegraph страницу: {str(e)}")

        return (
            f"https://telegra.ph/{response['path']}",
            f"https://graph.org/{response['path']}"
        )

    def _build_toc_content(
        self,
        chapters: List[Tuple[str, str, str, str, str]]
    ) -> List[Dict]:
        content = [
            {
                "tag": "p",
                "children": ["Создано Mangagraph, developer - ", {
                    "tag": "a",
                    "attrs": {"href": "https://t.me/damirtag"},
                    "children": ["@damirtag"]}
                ]
            }
        ]

        for volume, chapter_num, chapter_title, url, mirror_url in chapters:
            content.append({
                "tag": "p",
                "children": [
                    {
                        "tag": "a",
                        "attrs": {"href": mirror_url},
                        "children": [f"Volume {volume} Chapter {chapter_num}: {chapter_title}"]
                    }
                ]
            })

        return content

    async def _publish_toc(
        self,
        storage: MangaStorage,
        manga_name: str,
        chapters: List[Tuple[str, str, str, str, str]],
        existing_toc: Optional[TocRecord]
    ) -> Tuple[str, str]:
        """Создает оглавление или обновляет существующее при повторном запуске."""
        content = self._build_toc_content(chapters)

        try:
            if existing_toc is not None and existing_toc.path:
                await self.telegraph.edit_page(
                    path=existing_toc.path,
                    title=manga_name,
                    content=content
                )
                return existing_toc.url, existing_toc.mirror_url

            response = await self.telegraph.create_page(
                title=manga_name,
                author_name='Damir',
                author_url='https://github.com/damirtag/mangagraph',
                content=content
            )
        except MangagraphError:
            raise
        except Exception as e:
            raise MangagraphError(f'Telegraph says: {str(e)}')

        toc_url = response['url']
        mirror_toc_url = toc_url.replace("telegra.ph", "graph.org")

        storage.save_toc(
            manga_name=manga_name,
            url=toc_url,
            mirror_url=mirror_toc_url,
            path=response['path'],
            access_token=self.telegraph.access_token
        )

        return toc_url, mirror_toc_url

    async def process_manga(
        self, manga_url: str, db_name: Optional[str] = None
    ) -> Optional[Tuple[str, str]]:
        """
        Параметры:
            manga_url (str): URL манги, которую нужно обработать.
            db_name (str): Название файла базы данных, по дефолту дается по имени манги

        Возвращает:

            Кортеж из двух строк (либо None, если ни одна глава не обработана):

                - URL оглавления в Telegraph.

                - URL зеркала оглавления в graph.org (если используется).

        Исключения:
            MangagraphError: Выбрасывается, если возникает ошибка при обработке манги.
            InvalidURLException: Выбрасывается, если URL манги недействителен.
            RequestFailedException: Выбрасывается, если запрос к API завершается неудачей.
        """
        slug = extract_slug(manga_url)

        async with self.client:
            manga_name  = await self.client.get_manga_name(slug)
            chapters    = await self.client.get_chapters(slug)
            if not chapters:
                self.logger.error(f"Похоже, главы в манге были удалены: https://mangalib.me/ru/{slug}")
                return None

            storage = self._setup_storage(db_name or manga_name)
            try:
                # Продолжаем с тем же Telegraph-аккаунтом, чтобы можно было
                # редактировать уже созданное оглавление, а не плодить новые
                existing_toc: Optional[TocRecord] = storage.latest_toc()
                if existing_toc is not None and existing_toc.access_token:
                    self.telegraph.access_token = existing_toc.access_token
                else:
                    await self._ensure_telegraph_account()

                total_chapters = len(chapters)
                processed_count = 0
                processed_chapters = []
                failed_chapters = []

                for chapter_info in chapters:
                    volume = normalize_chapter_number(chapter_info.get('volume'))
                    chapter_num = normalize_chapter_number(chapter_info.get('number'))
                    title = (
                        f"{manga_name} | "
                        f"{chapter_info.get('name') or f'Том {volume}, Глава {chapter_num}'}"
                    )

                    existing_chapter = storage.get_chapter(volume, chapter_num)

                    if existing_chapter:
                        processed_count += 1
                        processed_chapters.append(
                            (volume, chapter_num, title, existing_chapter.url, existing_chapter.mirror_url)
                        )
                        remaining = total_chapters - processed_count
                        est_time = estimate_remaining_time(remaining)
                        self.logger.info(
                            f"Глава {chapter_num} уже существует, пропускаем... "
                            f"[{processed_count}/{total_chapters}] "
                            f"Примерное время: {est_time}"
                        )
                        continue

                    try:
                        pages = await self.client.get_chapter_pages(slug, volume, chapter_num)
                        if not pages:
                            raise MangagraphError("Страницы главы не найдены")

                        url, mirror_url = await self._create_telegraph_page(
                            title=title,
                            image_urls=pages
                        )

                        storage.add_chapter(
                            volume=volume,
                            chapter=chapter_num,
                            title=title,
                            url=url,
                            mirror_url=mirror_url
                        )

                        processed_count += 1
                        processed_chapters.append((volume, chapter_num, title, url, mirror_url))

                        remaining = total_chapters - processed_count
                        est_time = estimate_remaining_time(remaining)
                        self.logger.info(
                            f"Обработана глава: {title} "
                            f"[{processed_count}/{total_chapters}] "
                            f"Осталось: {est_time}"
                        )

                        await asyncio.sleep(3)

                    except Exception as e:
                        failed_chapters.append(chapter_num)
                        self.logger.error(
                            f"Ошибка обработки главы {chapter_num}: {str(e)}\n"
                            f"Всего обработано: {processed_count}/{total_chapters}"
                        )
                        continue

                if failed_chapters:
                    self.logger.warning(
                        f"Не удалось обработать {len(failed_chapters)} глав: "
                        f"{', '.join(failed_chapters)}. "
                        f"Повторный запуск обработает только их."
                    )

                if not processed_chapters:
                    return None

                toc_url, mirror_toc_url = await self._publish_toc(
                    storage,
                    manga_name,
                    processed_chapters,
                    existing_toc
                )

                self.logger.info(f"Создано оглавление: {toc_url}")
                self.logger.info(f"Всего обработано: {processed_count}/{total_chapters}")
                self.logger.info(f"Зеркало: {mirror_toc_url}")

                return toc_url, mirror_toc_url

            finally:
                storage.close()
                await self.telegraph.close()

    async def process_chapters(
        self,
        manga_url: str,
        chapter_nums: Union[ChapterNumber, List[ChapterNumber]],
        max_concurrent: int = 3
    ) -> Union[Optional[Tuple[str, str]], Dict[ChapterNumber, Optional[Tuple[str, str]]]]:
        """
        Обработка одной или несколько глав по ее номеру.

        Args:
            manga_url: URL манги из MangaLib
            chapter_nums: Номер одной главы (int/float/str, например 10 или "10.5")
                либо список глав
            max_concurrent: Maximum concurrent processing (default: 3)

        Returns:
            - Одна глава: Tuple[str, str] - (telegraph_url, mirror_url) or None
            - Список глав: Dict[chapter_num, Tuple[str, str]] - mapping chapter_num to URLs

        Examples:
        ```python
            # Одна глава
            url, mirror = await mg.process_chapters("https://mangalib.me/ru/manga/206--one-piece", 1050)

            # Несколько глав
            results = await mg.process_chapters("https://mangalib.me/ru/manga/206--one-piece", [1050, 1051, 1052])
        ```
        """
        is_single = isinstance(chapter_nums, (int, float, str))
        requested_chapters = [chapter_nums] if is_single else chapter_nums

        if not requested_chapters:
            self.logger.error("No chapters provided")
            return None if is_single else {}

        await self._ensure_telegraph_account()

        slug = extract_slug(manga_url)
        results = {}

        try:
            await self._process_chapters_batch(slug, requested_chapters, results, max_concurrent)
        finally:
            await self.telegraph.close()

        successful = sum(1 for v in results.values() if v is not None)
        self.logger.info(
            f"Обработка завершена: {successful}/{len(requested_chapters)} глав"
        )

        if is_single:
            return results.get(requested_chapters[0])
        return results

    async def _process_chapters_batch(
        self,
        slug: str,
        requested_chapters: List[ChapterNumber],
        results: Dict[ChapterNumber, Optional[Tuple[str, str]]],
        max_concurrent: int
    ):
        async with self.client:
            try:
                manga_name = await self.client.get_manga_name(slug)
            except Exception as e:
                self.logger.error(f"Failed to get manga name: {e}")
                return

            sem = asyncio.Semaphore(max_concurrent)

            async def process_single_chapter(chapter_num: ChapterNumber):
                async with sem:
                    try:
                        matches = await self.client.get_chapters(slug, chapter_num)
                        if not matches:
                            self.logger.error(
                                f"Глава №{chapter_num} не найдена, возможно удалена: "
                                f"https://mangalib.me/ru/{slug}"
                            )
                            results[chapter_num] = None
                            return

                        chapter = matches[0]
                        volume = chapter.get('volume')
                        number = chapter.get('number')
                        pages = await self.client.get_chapter_pages(slug, volume, number)

                        if not pages:
                            self.logger.error(f"Страниц для главы №{chapter_num} не найдено")
                            results[chapter_num] = None
                            return

                        title = (
                            f"{manga_name} | "
                            f"{chapter.get('name') or f'Том {volume}, Глава {number}'}"
                        )

                        url, mirror_url = await self._create_telegraph_page(
                            title=title,
                            image_urls=pages
                        )

                        self.logger.info(f"Обработана глава {chapter_num}: {title}")
                        results[chapter_num] = (url, mirror_url)

                        await asyncio.sleep(2)

                    except Exception as e:
                        self.logger.error(f"Error processing chapter {chapter_num}: {e}")
                        results[chapter_num] = None

            tasks = [process_single_chapter(num) for num in requested_chapters]
            await asyncio.gather(*tasks)
